堆栈去哪里了：在线程池中寻找堆栈
=======================================================================
我们先来看一个示例：
```java
package concurrent;

import java.sql.Time;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.SynchronousQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class Test1 {

    public static class DivTask implements Runnable {

        int a, b;

        public DivTask(int a, int b) {
            this.a = a;
            this.b = b;
        }

        @Override
        public void run() {
            double re = a / b;
            System.out.println(re);
        }
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        ThreadPoolExecutor pools = new ThreadPoolExecutor(
                0,
                Integer.MAX_VALUE,
                0L,
                TimeUnit.SECONDS,
                new SynchronousQueue<Runnable>());
        for (int i = 0; i < 5; i++) {
            pools.submit(new DivTask(100, i));
        }
    }
}
```
运行结果：
```
100.0
25.0
33.0
50.0
```
**只有4个输出，也就是说程序漏算了一组数据！！但更不坏的是，程序没有任何日志，没有任何错误提示，
就好像一切都正常一样**。在这个简单的案例中，只要你稍有经验，你就能发现，作为除数的`i`取到`0`，
这个缺失的值很可能是由于除以`0`导致的。但在稍复杂的业务场景中，这种错误足可以让你几天萎靡不振。

因此，使用线程池虽然是件好事，但是还是得处处留意这些“坑”。线程池很有可能会“吃”掉程序抛出的异常，
导致我们对程序的错误一无所知。

所以，这里我们将和大家讨论向线程池讨回异常堆栈的方法。一种最简单的方法，**就是放弃`submit()`，改用
`execute()`**。修改上面的示例：
```java
pools.execute(new DivTask(100,i));
```
打印结果：
```
100.0
50.0
33.0
25.0
Exception in thread "pool-1-thread-1" java.lang.ArithmeticException: / by zero
	at concurrent.Test1$DivTask.run(Test1.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
或者你 **使用下面的方法改造你的`submit()`**：
```java
Future re = pools.submit(new DivTask(100,i));
re.get();
```
打印消息：
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at concurrent.Test1.main(Test1.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArithmeticException: / by zero
	at concurrent.Test1$DivTask.run(Test1.java:19)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
上面两种方法都可以得到部分堆栈信息。
