用try表达式实现异常处理
================================================================================
**Scala的异常处理跟其他语言类似。方法除了正常地返回某个值外，也可以通过抛出异常终止执行**。方法
的调用方要么捕获并处理这个异常，要么自我终止，让异常传播到更上层调用方。异常通过这种方式传播，逐
个展开调用栈，直到某个方法处理该异常或者再没有更多方法了为止。

## 1.抛出异常
在Scala中抛出异常跟Java看上去一样。你需要 **创建一个异常对象然后用throw关键字将它抛出**：
```scala
throw new IllegalArgumentException
```
**在Scala中throw是一个有结果类型的表达式**。如下是一个带有结果类型的示例：
```scala
val half = 
  if (n % 2 == 0)
    n / 2
  else
    throw new RuntimeException("n must be even)
```
在这段代码中，如果`n`是偶数，`half`将被初始化成`n`的一半。如果`n`不是偶数，那么在`half`初始化
之前，就会有异常抛出。因此，**我们可以安全地将抛出异常当作任何类型的值来对待。任何想要使用throw
给出的这个返回值的上下文都没有机会真正使用它，也就不必担心有其他问题**。

技术上讲，**抛出异常这个表达式的类型是Nothing。哪怕表达式从不实际被求值，也可以用throw**。这个
技术细节听上去有点奇怪，不过在前一例这样的场景下，还是很常见也很有用的。if的一个分支计算出来某个
值，而另一个分支抛出异常并计算出Nothing。**整个if表达式的类型就是那个计算出某个值的分支的类型**。

## 2.捕获异常
可以使用下面示例中的语法来捕获异常。**catch子句的语法之所以是这样，为的是与Scala的一个重要组成
部分：*模式匹配*，保持一致**。
```scala

```


